### PR TITLE
Fix typo in string formatting usage example and drop Python 2.7 tests

### LINKED ISSUE #20: Special conversion specifiers do not work
Using the special conversion characters defined in https://trollsift.readthedocs.io/en/latest/api.html#trollsift.parser.StringFormatter do not work in Trollsift 0.3.4 with Python 3.7.6. The example in https://trollsift.readthedocs.io/en/latest/usage.html#composing

```python
from trollsift import Parser
my_parser = Parser("{platform_name:l}")
my_parser.compose({'platform_name': 'NPP'})
```

results in a crash:

```
ValueError                                Traceback (most recent call last)
<ipython-input-15-6d8ad0d4abdd> in <module>
----> 1 my_parser.compose({'platform_name': 'NPP'})

~/Software/miniconda3/envs/oper_20200210/lib/python3.7/site-packages/trollsift/parser.py in compose(self, keyvals)
     52         with values with the corresponding keys in *keyvals* dictionary.
     53         '''
---> 54         return compose(self.fmt, keyvals)
     55 
     56     format = compose

~/Software/miniconda3/envs/oper_20200210/lib/python3.7/site-packages/trollsift/parser.py in compose(fmt, keyvals)
    407 def compose(fmt, keyvals):
    408     """Convert parameters in `keyvals` to a string based on `fmt` string."""
--> 409     return formatter.format(fmt, **keyvals)
    410 
    411 

~/Software/miniconda3/envs/oper_20200210/lib/python3.7/string.py in format(*args, **kwargs)
    184             raise TypeError("format() missing 1 required positional "
    185                             "argument: 'format_string'") from None
--> 186         return self.vformat(format_string, args, kwargs)
    187 
    188     def vformat(self, format_string, args, kwargs):

~/Software/miniconda3/envs/oper_20200210/lib/python3.7/string.py in vformat(self, format_string, args, kwargs)
    188     def vformat(self, format_string, args, kwargs):
    189         used_args = set()
--> 190         result, _ = self._vformat(format_string, args, kwargs, used_args, 2)
    191         self.check_unused_args(used_args, args, kwargs)
    192         return result

~/Software/miniconda3/envs/oper_20200210/lib/python3.7/string.py in _vformat(self, format_string, args, kwargs, used_args, recursion_depth, auto_arg_index)
    241 
    242                 # format the object and append to the result
--> 243                 result.append(self.format_field(obj, format_spec))
    244 
    245         return ''.join(result), auto_arg_index

~/Software/miniconda3/envs/oper_20200210/lib/python3.7/string.py in format_field(self, value, format_spec)
    258 
    259     def format_field(self, value, format_spec):
--> 260         return format(value, format_spec)
    261 
    262 

ValueError: Unknown format code 'l' for object of type 'str'
```

The same happens when using `trollsift.compose('{platform_name:l}', {'platform_name': 'NPP'})`.

### PR DESCRIPTION
**Pull request by djhoese**
Closes #20 

Was a `:` in the docs, should be a `!`.

### CODE REVIEW

**Comment by djhoese** [comment]
Note: There was a small code change in the parser.py code for escape sequences because Python 3.7 was complaining about it. Based on the tests my updated code seems to be fine.
